In [1]:
# import matplotlib.pyplot as plt

In [2]:
import pandas as pd

In [3]:
import rbench as rb

In [4]:
groebner = rb.read_filetree('../benchmark-results/groebner/2022-05-23', 'groebner').select('boot')

In [5]:
type(groebner)

rbench.analytics.RbDataFrame

In [6]:
groebner

                           groebner                                \
                         start_boot cpu_boot gc_boot sigxcpu_boot
caprasse  2022-05-23 06:20:52+02:00     0.04    0.00         None
caprasse  2022-05-23 06:20:52+02:00     0.04    0.00         None
cassou    2022-05-23 06:20:24+02:00     0.26    0.01         None
cyclic10  2022-05-23 06:20:27+02:00    29.08    0.01         None
cyclic10  2022-05-23 06:20:27+02:00    29.08    0.01         None
cyclic11  2022-05-23 06:20:25+02:00   174.04    0.02         None
cyclic12  2022-05-23 06:20:53+02:00      NaN     NaN          180
cyclic12  2022-05-23 06:20:53+02:00      NaN     NaN          180
cyclic5   2022-05-23 06:20:24+02:00     0.01    0.00         None
cyclic6   2022-05-23 06:20:51+02:00     0.02    0.01         None
cyclic6   2022-05-23 06:20:51+02:00     0.02    0.01         None
cyclic7   2022-05-23 06:20:40+02:00     0.13    0.01         None
cyclic7   2022-05-23 06:20:40+02:00     0.13    0.01         None
cyclic8   2022-05-23 06:20:49+02:00     0.80    0.00         None
cyclic8   2022-05-23 06:20:49+02:00     0.80    0.00         None
cyclic9   2022-05-23 06:20:41+02:00     4.80    0.01         None
cyclic9   2022-05-23 06:20:41+02:00     4.80    0.01         None
eco5      2022-05-23 06:21:20+02:00     0.02    0.00         None
eco5      2022-05-23 06:21:20+02:00     0.02    0.00         None
eco7      2022-05-23 06:20:39+02:00     0.80    0.01         None
eco7      2022-05-23 06:20:39+02:00     0.80    0.01         None
hairer1   2022-05-23 06:20:47+02:00     0.03    0.01         None
hairer1   2022-05-23 06:20:47+02:00     0.03    0.01         None
hairer2   2022-05-23 06:20:24+02:00      NaN     NaN          180
henrion5  2022-05-23 06:20:27+02:00    10.12    0.01         None
henrion6  2022-05-23 06:21:12+02:00      NaN     NaN          180
henrion6  2022-05-23 06:21:12+02:00      NaN     NaN          180
katsura6  2022-05-23 06:20:52+02:00     3.80    0.00         None
katsura6  2022-05-23 06:20:52+02:00     3.80    0.00         None
katsura7  2022-05-23 06:21:19+02:00     0.00    0.01         None
katsura7  2022-05-23 06:21:19+02:00     0.00    0.01         None
kinema    2022-05-23 06:21:08+02:00     2.73    0.01         None
kinema    2022-05-23 06:21:08+02:00     2.73    0.01         None
ku10      2022-05-23 06:20:51+02:00     0.04    0.01         None
ku10      2022-05-23 06:20:51+02:00     0.04    0.01         None
nbody4    2022-05-23 06:20:24+02:00    38.68    0.00         None
nbody4sym 2022-05-23 06:20:57+02:00      NaN     NaN          180
nbody4sym 2022-05-23 06:20:57+02:00      NaN     NaN          180
nbody5    2022-05-23 06:20:25+02:00    47.64    0.02         None
noon4     2022-05-23 06:20:48+02:00     0.07    0.01         None
noon4     2022-05-23 06:20:48+02:00     0.07    0.01         None
noon5     2022-05-23 06:20:47+02:00     2.83    0.01         None
noon5     2022-05-23 06:20:47+02:00     2.83    0.01         None
noon6     2022-05-23 06:20:24+02:00    19.66    0.00         None
noon7     2022-05-23 06:20:24+02:00      NaN     NaN          180
noon8     2022-05-23 06:20:24+02:00      NaN     NaN          180
ojika4    2022-05-23 06:21:22+02:00     0.02    0.00         None
ojika4    2022-05-23 06:21:22+02:00     0.02    0.00         None
sparse5   2022-05-23 06:21:21+02:00     0.00    0.02         None
sparse5   2022-05-23 06:21:21+02:00     0.00    0.02         None
trinks    2022-05-23 06:20:59+02:00      NaN     NaN          180
trinks    2022-05-23 06:20:59+02:00      NaN     NaN          180


          heapsize_boot valid_boot                  end_boot
caprasse           None       None 2022-05-23 06:20:53+02:00
caprasse           None       None 2022-05-23 06:20:53+02:00
cassou             None       None 2022-05-23 06:20:27+02:00
cyclic10           None       None 2022-05-23 06:20:59+02:00
cyclic10           None       None 2022-05-23 06:20:59+02:00
cyclic11           None       None 2022-05-23 06:23:40+02:00
cyclic12           None       None 2022-05-23 06:24:08+02:00
cyclic12           None       None 2022-05-23 06:24:08+02:00
cyclic5            None       None 2022-05-23 06:20:27+02:00
cyclic6            None       None 2022-05-23 06:20:52+02:00
cyclic6            None       None 2022-05-23 06:20:52+02:00
cyclic7            None       None 2022-05-23 06:20:41+02:00
cyclic7            None       None 2022-05-23 06:20:41+02:00
cyclic8            None       None 2022-05-23 06:20:51+02:00
cyclic8            None       None 2022-05-23 06:20:51+02:00
cyclic9            None       None 2022-05-23 06:20:47+02:00
cyclic9            None       None 2022-05-23 06:20:47+02:00
eco5               None       None 2022-05-23 06:21:21+02:00
eco5               None       None 2022-05-23 06:21:21+02:00
eco7               None       None 2022-05-23 06:20:40+02:00
eco7               None       None 2022-05-23 06:20:40+02:00
hairer1            None       None 2022-05-23 06:20:48+02:00
hairer1            None       None 2022-05-23 06:20:48+02:00
hairer2            None       None 2022-05-23 06:23:36+02:00
henrion5           None       None 2022-05-23 06:20:39+02:00
henrion6           None       None 2022-05-23 06:24:31+02:00
henrion6           None       None 2022-05-23 06:24:31+02:00
katsura6           None       None 2022-05-23 06:20:57+02:00
katsura6           None       None 2022-05-23 06:20:57+02:00
katsura7           None       None 2022-05-23 06:21:20+02:00
katsura7           None       None 2022-05-23 06:21:20+02:00
kinema             None       None 2022-05-23 06:21:12+02:00
kinema             None       None 2022-05-23 06:21:12+02:00
ku10               None       None 2022-05-23 06:20:52+02:00
ku10               None       None 2022-05-23 06:20:52+02:00
nbody4             None       None 2022-05-23 06:21:08+02:00
nbody4sym          None       None 2022-05-23 06:24:22+02:00
nbody4sym          None       None 2022-05-23 06:24:22+02:00
nbody5             None       None 2022-05-23 06:21:19+02:00
noon4              None       None 2022-05-23 06:20:49+02:00
noon4              None       None 2022-05-23 06:20:49+02:00
noon5              None       None 2022-05-23 06:20:51+02:00
noon5              None       None 2022-05-23 06:20:51+02:00
noon6              None       None 2022-05-23 06:20:47+02:00
noon7              None       None 2022-05-23 06:23:32+02:00
noon8              None       None 2022-05-23 06:23:33+02:00
ojika4             None       None 2022-05-23 06:21:22+02:00
ojika4             None       None 2022-05-23 06:21:22+02:00
sparse5            None       None 2022-05-23 06:21:22+02:00
sparse5            None       None 2022-05-23 06:21:22+02:00
trinks             None       None 2022-05-23 06:24:08+02:00
trinks             None       None 2022-05-23 06:24:08+02:00

In [ ]:
groebner.plot.schedule()

In [ ]:
groebner

In [ ]:
f5 = rb.read_filetree('../benchmark-results/f5/2022-05-23', 'f5').select('boot')

In [ ]:
f5.plot.schedule()

In [ ]:
f5

In [ ]:
combo = pd.concat([groebner, f5], axis=1)

In [ ]:
mwe1 = rb.RbDataFrame.from_dict({('becnhmark1', 'data1'): [1, 2, 3]}).rename(index={0: 'w', 1: 'x', 2: 'y'})

In [ ]:
mwe1

In [ ]:
mwe2 = rb.RbDataFrame.from_dict({('benchmark2', 'data1'): [4, 5, 6]}).rename(index={0: 'x', 1: 'y', 2: 'z'})

In [ ]:
mwe2

In [ ]:
pd.concat([mwe1, mwe2], axis=1)

In [ ]:
mwe1.join(mwe2, how='inner')

In [ ]:
type(mwe1)